name: Create rezi.csv
on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

jobs:
  rezi:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install deps and run main.py
        run: |
          pip install -r requirements.txt
          python3 main.py

      - name: Upload rezi.csv
        uses: actions/upload-artifact@v3
        with:
          name: rezi.csv
          path: ${{ github.workspace }}/rezi.csv

      - name: Delete previous release
        uses: dev-drprasad/delete-older-releases@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 3
          delete_tags: true

      - name: Create new release
        uses: ncipollo/release-action@v1.12.0
        with:
          commit: main
          tag: rezi
          artifacts: rezi.csv
          body: Download the file to get the most recent deploy!
