name: Create rezi.csv
on: [push]

jobs:
  rezi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps and run main.py
        run: |
          pip install -r requirements.txt
          python3 main.py

      - name: Upload rezi.csv
        uses: actions/upload-artifact@v3
        with:
          name: rezi.csv
          path: ${{ github.workspace }}/rezi.csv

      - name: Delete previous release
        uses: dev-drprasad/delete-older-releases@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 3
          delete_tags: true

      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          tag-name: rezi
          name: ${{ steps.utils.output.date }}
          body: Download the file to get the most recent deploy!
          files: ${{ github.workspace }}/rezi.csv
          draft: false
          prerelease: false
